# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f5073cfd4131848ebb590a955b1500c5688b39a9d7e1741102f3e0ce7d79f3c8317e83ca32b0d96bda85db4f029c220af9b096eb819a51bbfe477749070bf12

test:
  secret_key_base: 78aa277422c821a5def285b7d5d084fa3a7ae77789eafb33fe4d1a8de5f5ecc698c4fa6df3553246dcf1233ad9c1b685474abaf8b5608481b26962fc929039ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
